name: apple_lockdown_mode
description: Handy flutter plugin which simplifies apple lockdown mode detection.
version: 0.0.1
repository: https://github.com/Code-Growers/apple_lockdown_mode
issue_tracker: https://github.com/Code-Growers/apple_lockdown_mode/issues
homepage: https://codegrowers.tech

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AppleLockdownModePlugin
